title:   Ryan Zhang
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A perceptive and logical individual with proven ability to analyze Data with advanced use of Power BI, SQL, Python, Tableau and Excel, proven ability to develop valuable process solutions to meet business objectives.
  <br>
  <br>
  I'm also an Environmental Specialist based in GTA, responsible for both environmental field work and report preparation, experience in environmental & civil engineering and sales industries.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/yuyang-zhang3653/">View My LinkedIn Profile</a>
  <br>
  <a href="https://public.tableau.com/app/profile/ryanz8405#!/?newProfile=&activeTab=0">View My Tableau Work Samples</a>
  <br>
  <a href="https://www.notion.so/ryan-zhang/Ryan-s-Portfolio-b4e2c978b84f42f8a1fea8465aff6e2e">View My Notion Portfolios</a>

theme: jekyll-theme-minimal
