title:   Ryan Zhang
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm currenly an Environmental Specialist based in Vaughan, responsible for both environmental field work and report preparation, experience in environmental & civil engineering and sales industries.
  <br><br>
  I'm also experienced in data analytics with advance use of python, SQL, Power BI, Tableau and Excel
  <br><br>
  <a href="https://www.linkedin.com/in/shuchangl/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/elvisliang/About-Me-Elvis-Liang-3f4f047d65c5438a8d70686f9e849254">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
